---
# Optimized golangci-lint configuration
# Focuses on critical linters for fast, accurate code quality checks

version: "2"

run:
  timeout: 5m  # Sufficient for local and CI environments
  go: "1.25"
  concurrency: 4  # Parallel processing for faster execution
  build-tags:
    - integration

linters:
  # Enable only critical linters for CI performance
  enable:
    - errcheck      # Critical: unhandled errors
    - gosec         # Critical: security issues
    - govet         # Critical: suspicious constructs
    - ineffassign   # Critical: ineffective assignments
    - staticcheck   # Critical: static analysis
    - unused        # Critical: unused code
    - misspell      # Critical: common misspellings
    - whitespace    # Critical: whitespace formatting
    - revive        # Critical: general linting rules (faster than golint)

  # Disable slower linters that can be run locally/in development
  disable:
    - bodyclose     # Slower: HTTP response body checks
    - dupl          # Slower: duplicate code detection
    - exhaustive    # Slower: exhaustive switch statements
    - funlen        # Slower: function length
    - gochecknoinits # Slower: init function checks
    - goconst       # Slower: constant extraction
    - gocritic      # Slower: comprehensive criticism
    - gocyclo       # Slower: cyclomatic complexity
    - lll           # Slower: line length
    - nakedret      # Slower: naked returns
    - noctx         # Slower: context checks
    - nolintlint    # Slower: lint directive checks
    - rowserrcheck  # Slower: SQL row error checks
    - unconvert     # Slower: unnecessary conversions
    - unparam       # Slower: unused parameters

issues:
  max-issues-per-linter: 0   # Report all issues
  max-same-issues: 0         # Report all duplicate issues
  exclude-use-default: false # Don't exclude common issues
  exclude-dirs:
    - vendor
    - node_modules
    - tmp
    - .git
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*_test\\.go$"
  exclude:
    # Exclude false positive from revive var-naming for standard package names
    - "var-naming: avoid meaningless package names"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  gosec:
    severity: high  # Only report high severity issues in CI
    confidence: medium

  govet:
    enable-all: false
    enable:
      - atomic
      - bools
      - copylocks
      - printf
      - shadow
      - shift
      - unreachable

  revive:
    rules:
      - name: var-naming
        disabled: true  # Disable to avoid false positives on standard package names (e.g., "api")
      - name: package-comments
        disabled: true  # Disable for speed

output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: false  # Reduce output for CI performance
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
