version: "2"

run:
  timeout: 5m
  go: "1.24"

linters:
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
