version: "2"

run:
  timeout: 5m
  go: "1.23"

linters-settings:
  dupl:
    threshold: 100
  funlen:
    lines: 100
    statements: 50
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/radarr/radarr-go)
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
      - hugeParam
  gocyclo:
    min-complexity: 15
  govet:
    enable-all: true
    disable:
      - fieldalignment # Too noisy for now
  lll:
    line-length: 140
  misspell:
    locale: US
  gosec:
    severity: medium
    confidence: medium

linters:
  disable-all: true
  enable:
    - bodyclose
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - mnd
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: ""
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - funlen
        - gocyclo
        - dupl
    - path: cmd/
      linters:
        - gochecknoinits
    - path: internal/models/
      linters:
        - lll
    - linters:
        - lll
      source: "^//go:generate "
  exclude-dirs:
    - vendor/
  exclude-files:
    - ".*\\.pb\\.go$"