server:
  port: 7878
  host: "0.0.0.0"
  url_base: ""
  enable_ssl: false
  ssl_cert_path: ""
  ssl_key_path: ""

database:
  type: "postgres"  # Options: mariadb, mysql, postgres, postgresql
  host: "localhost"
  port: 5432
  database: "radarr"
  username: "radarr"
  password: "${RADARR_DATABASE_PASSWORD:-}"
  connection_url: ""  # Optional: Override individual settings with full connection string
  max_connections: 10

log:
  level: "info"
  format: "json"
  output: "stdout"

auth:
  method: "none"
  api_key: ""

storage:
  data_directory: "./data"
  movie_directory: "./data/movies"
  backup_directory: "./data/backups"

tmdb:
  api_key: ""  # Get from https://www.themoviedb.org/settings/api
