server:
  port: 7878

database:
  type: "postgres"
  host: "localhost"
  port: 5432
  database: "radarr_test"
  username: "test_user"
  password: "${RADARR_TEST_DB_PASSWORD:-secure_test_password}"

log:
  level: "debug"
