# Docker Compose file for test databases

services:
  # PostgreSQL test database
  postgres-test:
    image: postgres:17-alpine
    container_name: radarr-postgres-test
    environment:
      - POSTGRES_DB=radarr_test
      - POSTGRES_USER=radarr_test
      - POSTGRES_PASSWORD=test_password
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    ports:
      - "15432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U radarr_test -d radarr_test"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    tmpfs:
      - /tmp
      - /var/run/postgresql
    shm_size: 64mb

  # MariaDB test database
  mariadb-test:
    image: mariadb:11.4
    container_name: radarr-mariadb-test
    environment:
      - MARIADB_DATABASE=radarr_test
      - MARIADB_USER=radarr_test
      - MARIADB_PASSWORD=test_password
      - MARIADB_ROOT_PASSWORD=root_test_password
      - MARIADB_INITDB_SKIP_TZINFO=1
    ports:
      - "13306:3306"
    volumes:
      - mariadb_test_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=64M
      --innodb-log-file-size=16M
      --innodb-flush-log-at-trx-commit=2
      --sync-binlog=0
      --innodb-doublewrite=0
    tmpfs:
      - /tmp
      - /var/run/mysqld

  # Test runner service (optional - for running tests in container)
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: radarr-test-runner
    depends_on:
      postgres-test:
        condition: service_healthy
      mariadb-test:
        condition: service_healthy
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
    volumes:
      - .:/workspace
      - test_cache:/go/pkg/mod
      - test_build_cache:/root/.cache/go-build
    working_dir: /workspace
    profiles:
      - test-runner

volumes:
  postgres_test_data:
    driver: local
  mariadb_test_data:
    driver: local
  test_cache:
    driver: local
  test_build_cache:
    driver: local

networks:
  default:
    name: radarr-test-network
    driver: bridge