# docker-compose.test.yml - Testing Environment
# Minimal services for running tests
# Usage: docker-compose -f docker-compose.yml -f docker-compose.test.yml up --profile test

services:
  # Test databases use separate ports and optimized for fast startup
  postgres-test:
    profiles:
      - test
    ports:
      - "15432:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=radarr_test
      - POSTGRES_USER=radarr_test
      - POSTGRES_PASSWORD=test_password
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    tmpfs:
      - /tmp
      - /var/run/postgresql
    shm_size: 64mb
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c checkpoint_segments=32
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB

  mariadb-test:
    profiles:
      - test
      - mariadb
    ports:
      - "13306:3306"
    volumes:
      - mariadb_test_data:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=radarr_test
      - MARIADB_USER=radarr_test
      - MARIADB_PASSWORD=test_password
      - MARIADB_ROOT_PASSWORD=root_test_password
    healthcheck:
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    tmpfs:
      - /tmp
      - /var/run/mysqld
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=64M
      --innodb-log-file-size=16M
      --innodb-flush-log-at-trx-commit=2
      --sync-binlog=0
      --innodb-doublewrite=0
      --innodb-flush-method=O_DIRECT

  # Optional test runner service
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: radarr-test-runner
    depends_on:
      postgres-test:
        condition: service_healthy
      mariadb-test:
        condition: service_healthy
    environment:
      - CGO_ENABLED=0
      - GOOS=linux
      - GOARCH=amd64
      - RADARR_DATABASE_TYPE=postgres
      - RADARR_DATABASE_HOST=postgres-test
      - RADARR_DATABASE_PORT=5432
      - RADARR_DATABASE_USERNAME=radarr_test
      - RADARR_DATABASE_PASSWORD=test_password
      - RADARR_DATABASE_NAME=radarr_test
    volumes:
      - .:/workspace
      - test_cache:/go/pkg/mod
      - test_build_cache:/root/.cache/go-build
    working_dir: /workspace
    profiles:
      - test-runner
    networks:
      - test-network

# Test-specific volumes (use faster tmpfs where possible)
volumes:
  test_cache:
    driver: local
  test_build_cache:
    driver: local

# Test network isolation
networks:
  test-network:
    name: radarr-test-network
    driver: bridge
